services:
  postgres-dwh:
    image: postgres:latest
    container_name: postgres-dwh
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dwh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql



      
