services:
  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: airflow standalone

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: dwh
    ports:
      - "5432:5432"